# makoctl reload

[app-name=mononotif]
layer=overlay
history=0
anchor=top-right
# Group all notifications together
group-by=app-name
# Hide the group-index
format=<b>%s</b>\n%b

[app-name=mononotif group-index=0]
# Only show last notification
invisible=0
