#!/usr/bin/env bash

# hides the mouse after 3 seconds of inactivity
nohup unclutter -idle 3 &> /dev/null &

# disable mouse by default
mouse off

# fetch git repos
nohup ~/.dotfiles/gitfetch.sh &> /dev/null

# dwm status
nohup ~/.dotfiles/dwm/daemonstatus.sh &> /dev/null &
