#!/usr/bin/env bash

# start window manager
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
  echo Starting Window Manager...
  sleep 1
  exec startx
fi

# hides the mouse after 3 seconds of inactivity
nohup unclutter -idle 3 &> /dev/null &

# disable mouse by default
mousetoggle off

# fetch git repos
nohup autogitfetch &> /dev/null

# dwm status
nohup $HOME/.dotfiles/dwm/daemonstatus.sh &> /dev/null &

webtest
