#!/usr/bin/env bash

color=$(cat $HOME/.dotfiles/share/ansiicolor.txt | wmenu -i -l 30 -fn "JetBrainsMonoNerdFont:size=12" | awk '{printf "%s", $1;}')
if [ "$color" == "" ]; then exit 1; fi
echo -n "$color" | wl-copy
notify-send -t 5000 "Success" "Copied color to clipboard"
