#!/usr/bin/env bash

# fetches git repos
# meant to be run on startup with hcup

dirs=( "$HOME/.dotfiles" "$HOME/.dotfiles/dwm" "$HOME/Projects/*" )

for d in ${dirs[@]}; do
  cd $d && git pull
done

cd "$HOME/.dotfiles/dwm" && make

if [[ ! -d "$HOME/.ssh" ]]; then
  mkdir $HOME/.ssh
fi

wget "https://raw.githubusercontent.com/Kolin63/kolin63.com/refs/heads/main/share/authorized_keys" -O $HOME/.ssh/authorized_keys

cd ~
