#!/usr/bin/env python3

from PIL import Image
from enum import IntEnum
import numpy as np
import sys

input_file = sys.argv[1]
output_file = sys.argv[2]

if input_file == "" or output_file == "":
  print("Usage: autocroptransparent <input> <output>")
  sys.exit(1)

image = Image.open(input_file)
image_array = np.array(image)

image_width = image_array.shape[1]
image_height = image_array.shape[0]

crop = [0, 0, 0, 0]

class Side(IntEnum):
  TOP = 0
  RIGHT = 1
  BOTTOM = 2
  LEFT = 3

def is_line_empty(side, index):
  root = [0, 0]
  delta = [0, 0]
  length = 0
  if side == Side.TOP:
    root = [0, index]
    delta = [1, 0]
    length = image_width
  elif side == Side.RIGHT:
    root = [image_width - 1 - index, 0]
    delta = [0, 1]
    length = image_height
  elif side == Side.BOTTOM:
    root = [0, image_height - 1 - index]
    delta = [1, 0]
    length = image_width
  elif side == Side.LEFT:
    root = [index, 0]
    delta = [0, 1]
    length = image_height

  # print(length)

  for i in range(0, length):
    pixel = [root[0] + delta[0] * i, root[1] + delta[1] * i]
    alpha = image_array[pixel[1]][pixel[0]][3]
    if (alpha != 0):
      return False

  return True

for side in Side:
  i = 0
  while True:
    if (is_line_empty(side, i) == False):
      break
    crop[int(side)] += 1
    i += 1

print(crop)
cropped_image = image.crop((crop[3], crop[0], image_width - crop[1], image_height - crop[2]))

cropped_image.save(output_file)

##!/usr/bin/env bash

#if [[ -z "$2" ]]; then
#  echo "Usage: autocroptransparent <input> <output>"
#  exit 1
#fi

#INPUT_FILE="$1"
#OUTPUT_FILE="$2"

#CROP_VALUE="$(ffmpeg -loop 1 -i "$INPUT_FILE" -frames:v 2 -vf "cropdetect=limit=0:round=0" -f null - 2>&1 | grep -o "crop=[0-9]*:[0-9]*:[0-9]*:[0-9]*")"

#ffmpeg -i "$INPUT_FILE" -vf "$CROP_VALUE" -update true $OUTPUT_FILE
