#!/usr/bin/env bash

# fetches git repos
# meant to be run on startup with hcup

dirs=( "$HOME/.dotfiles" "$HOME/.dotfiles/dwm" "$HOME/Projects/*" )

for d in ${dirs[@]}; do
  cd $d && git pull
done

cd "$HOME/.dotfiles/dwm" && make

if [[ -e "$HOME/.ssh/authorized_keys" ]]; then
  wget https://kolin63.com/ssh -O "$HOME/.ssh/authorized_keys"
fi

cd ~
