#!/usr/bin/env bash

emoji=$(cat $HOME/.dotfiles/share/emojis.txt | wmenu -i -l 30 -fn "JetBrainsMono Nerd Font:size=12" | awk '{printf "%s", $1;}')
if [ "$emoji" == "" ]; then exit 1; fi
echo -n "$emoji" | wl-copy
notify-send -t 5000 "Success" "Emoji copied to clipboard"
