#!/usr/bin/env bash

raw=$(upower -b)
perc=$(echo "$raw" | grep "perc" | awk '{print $2}')
tm=$(echo "$raw" | grep "time" | awk '{printf $4; printf " "; print $5}')

msg="$(echo -e "$perc\n$tm")"

echo "$msg"

notify-send -t 5000 -a 'power' -h string:x-canonical-private-synchronous:power -h int:value:$perc "$msg"
