#!/usr/bin/env bash

host="kolin63.com"

(wget --timeout=5 --tries=1 $host -O /dev/null && notify-send "$host is OK" || notify-send -u critical "Uh Oh!" "Hostname $host is not responding") &> /dev/null &
