#!/usr/bin/env bash

line=$(( ($RANDOM % 142) + 1 ))

content=$(cat "$HOME/.dotfiles/share/artofwar.txt" | head -$line | tail -1)

body="$content\n\n  - Sun Tzu, The Art of War"

echo -e "$body" | cowsay
